name: CI

on:
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  scrape:
    name: Scrape Data
    runs-on: ubuntu-latest
    env:
      PYTHON: "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: |
          poetry install --no-interaction
      - name: Scrape Data
        run: |
          source $VENV
          python run main.py
        timeout-minutes: 30
      - name: Upload Data Artifact
        uses: actions/upload-artifact@v2
        with:
          name: data
          path: duck.db